### ISSUE TITLE
Clear Files feature doesn't work

### ISSUE THREAD

**Issue by Reda-BENMAKDAD** [ThatGuyCalledJesse/fileserver#11]
## Expected behavior:
click on the **"clear files"** button, navigate to the _**/download**_ endpoint and find it blank.

## Actual behavior:
 when i click on the **"clear files"** button, it shows **"Files Cleared"**, but when i go to the _**/download**_ endpoint, my files are still there

_**Steps to reproduce**_

1. clone the repository and start the server
2. navigate to the **_/upload_** endpoint and upload a file
3. clear all files with the clear files button
4. navigate to the _**/download**_ and file is still there

## Environement:
- Python 3.10
- Flask version 2.0.2
-  Windows 10 machine

**Comment by ThatGuyCalledJesse** [comment]
I'll have a look, for me it worked fine

**Comment by ThatGuyCalledJesse** [comment]
For me it works. When I upload and file press `clear files` the file is then removed from the server

**Comment by ThatGuyCalledJesse** [comment]
I have python 3.11 installed, maybe that is something but I don't think it matters

**Comment by ThatGuyCalledJesse** [comment]
Is there something unusual in the console log?

**Comment by Reda-BENMAKDAD** [comment]
ok so good that you said that because there was actually an error log in the terminal that i didn't see, the problem is in the _**clear_files**_ function, it uses _**rm**_ to delete files but i'm on windows and rm doesn't exist, i'm gonna change the way files  are deleted so that it is plateform independent real quick

**Comment by ThatGuyCalledJesse** [comment]
I'll see if I can change that right now and push it to main

**Comment by ThatGuyCalledJesse** [comment]
I see you made a pull request already, can you `git pull` to update the repo and test it before I close this issue?

**Comment by Reda-BENMAKDAD** [comment]
> update

i'm already up to date and you merged, i think you can close the issue and discussion 👍🏼
